# PostgreSQL

default: &default
  adapter:  postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
  username: catchall
  password: catchall!


development:
  <<: *default
  database: catchall_development

test:
  <<: *default
  database: catchall_test

production:
  <<: *default
  database: catchall_production